//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Kategori
    {
        public int ID_KategoriWilayah { get; set; }
        public int ID_Kota { get; set; }
        public int Status { get; set; }
    
        public virtual Kategori_Wilayah Kategori_Wilayah { get; set; }
        public virtual Kota Kota { get; set; }
    }
}
