//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Detail_PaketMetadata))]
    public partial class Detail_Paket
    {
        public int ID_Paket { get; set; }
        public int ID_Destinasi { get; set; }
        public int Status { get; set; }
    
        public virtual Destinasi Destinasi { get; set; }
        public virtual Paket Paket { get; set; }
    }
}
