//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Rating_Destinasi
    {
        public string NIK { get; set; }
        public int ID_Destinasi { get; set; }
        public int Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Destinasi Destinasi { get; set; }
    }
}
