//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kendaraan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kendaraan()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
    
        public int ID_Kendaraan { get; set; }
        public string Nama_Kendaraan { get; set; }
        public int ID_Jenis { get; set; }
        public string No_Kendaraan { get; set; }
        public decimal Harga_kendaraan { get; set; }
        public int Status { get; set; }
    
        public virtual Jenis_Kendaraan Jenis_Kendaraan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
