//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using BUSS.Models;
    
    [MetadataType(typeof(PegawaiMetadata))]
    public partial class Pegawai
    {
        public int ID_Pegawai { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public string No_HP { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public int Status { get; set; }
    }
}
