//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_LaporanFeedback
    {
        public int ID_Feedback { get; set; }
        public int ID_Transaksi { get; set; }
        public int Rating { get; set; }
        public string Isi_Feedback { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Nama_Paket { get; set; }
        public Nullable<int> Lama_Perjalanan { get; set; }
        public System.DateTime Tanggal_Pesanan { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public string Email { get; set; }
    }
}
