//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_JumlahDestinasiWilayah
    {
        public int ID_KategoriWilayah { get; set; }
        public string Nama_Wilayah { get; set; }
        public Nullable<int> JumlahDestinasi { get; set; }
    }
}
