//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_TransaksiCustomer
    {
        public int ID_Transaksi { get; set; }
        public int ID_Paket { get; set; }
        public string ID_Customer { get; set; }
        public Nullable<int> ID_Pegawai { get; set; }
        public decimal Harga_total { get; set; }
        public int Jumlah_Penumpang { get; set; }
        public System.DateTime Tanggal_Pesanan { get; set; }
        public string Bukti_DP { get; set; }
        public string Bukti_Pelunasan { get; set; }
        public Nullable<decimal> biaya_tambahan { get; set; }
        public int Status_Transaksi { get; set; }
        public Nullable<double> PaketLama_Perjalanan { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime CreatedDateTr { get; set; }
        public string Nama_Paket { get; set; }
        public Nullable<decimal> Harga { get; set; }
        public int Konsumsi { get; set; }
        public Nullable<int> Lama_Perjalanan { get; set; }
        public int Penginapan { get; set; }
        public int Jenis_Paket { get; set; }
        public string Jadwal { get; set; }
        public string Keterangan { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
