//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_DestinasiTerlaris
    {
        public int ID_Destinasi { get; set; }
        public string Nama_Destinasi { get; set; }
        public Nullable<int> JumlahDipesan { get; set; }
    }
}
